services:
  server:
    build:
      context: ./server
      args:
        SECRET_KEY: secret
    container_name: server
    restart: unless-stopped
    user: 1000:1000
    environment:
      - JWT_SECRET=change_me! # use `openssl rand -hex 32` to generate a strong secret
      - SECRET_KEY=secret
    ports:
      - "3000:3000"
  client:
    build:
      context: ./client
      args:
        API_URL: http://localhost:3000
        SECRET_KEY: secret
    container_name: client
    restart: unless-stopped
    user: 1000:1000
    environment:
      - API_URL=http://localhost:3000
      - SECRET_KEY=secret
    ports:
      - "3001:3001"
