services:
  server:
    build:
      context: ./server
      args:
        - NODE_ENV=production
    container_name: server
    restart: unless-stopped
    user: 1000:1000
    environment:
      - PORT
      - JWT_SECRET=jwt_secret # change_me! # use `openssl rand -hex 32` to generate a strong secret
      - SECRET_KEY=secret # change me!
      - MEMORY_DB
      - REGISTRATION_PASSWORD
      - WELCOME_CONTENT
      - WELCOME_TITLE
      - ENABLE_ADMIN
      - DRIFT_HOME
    ports:
      - "3000:3000"
  client:
    build:
      context: ./client
      args:
        - API_URL=http://server:3000
    container_name: client
    restart: unless-stopped
    user: 1000:1000
    environment:
      - API_URL=http://server:3000
      - SECRET_KEY=secret # change me!
    ports:
      - "3001:3001"
